Function.prototype.bind||(Function.prototype.bind=function(b){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var d=Array.prototype.slice.call(arguments,1),a=this,f=function(){},c=function(){return a.apply(this instanceof f&&b?this:b,d.concat(Array.prototype.slice.call(arguments)))};f.prototype=this.prototype;c.prototype=new f;return c});
Array.prototype.forEach||(Array.prototype.forEach=function(b,d){for(var a=0,f=this.length;a<f;a++)a in this&&b.call(d,this[a],a,this)});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});window.AdTrack||(window.AdTrack={},window.AdTrack.units={});
window.AdTrack.JSON||(window.AdTrack.JSON={parse:function(b){return eval("("+b+")")},stringify:function(){var b=Object.prototype.toString,d=Array.isArray||function(a){return"[object Array]"===b.call(a)},a={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},f=function(b){return a[b]||"\\u"+(b.charCodeAt(0)+65536).toString(16).substr(1)},c=/[\\"\u0000-\u001F\u2028\u2029]/g;return function k(a){if(null==a)return"null";if("number"===typeof a)return isFinite(a)?a.toString():
"null";if("boolean"===typeof a)return a.toString();if("object"===typeof a){if("function"===typeof a.toJSON)return k(a.toJSON());if(d(a)){for(var h="[",e=0;e<a.length;e++)h+=(e?", ":"")+k(a[e]);return h+"]"}if("[object Object]"===b.call(a)){h=[];for(e in a)a.hasOwnProperty(e)&&h.push(k(e)+": "+k(a[e]));return"{"+h.join(", ")+"}"}}return'"'+a.toString().replace(c,f)+'"'}}()});AdTrack.AdFormUtils=function(){};
AdTrack.AdFormUtils.prototype={generateAdxUrl:function(b,d,a){var f={test:!0,url:!0,tid:!0,rp:!0,pv:!0,adxjs:!0,lat:!0,lon:!0},c=[],l=[];a=a||"pbjs._adf";if(!Array.isArray(b))return console.error("Placement id list should be an array.");for(var k=0;k<b.length;k++)l.push("mid="+b[k]);for(var g in d)if(d.hasOwnProperty(g)&&Array.isArray(d[g])){b=d[g];for(var h in b)b.hasOwnProperty(h)&&(f[g]?c.push(g+"="+encodeURIComponent(h)):l.push(g+"="+d[g]))}else f[g]?c.push(g+"="+encodeURIComponent(d[g])):l.push(g+
"="+d[g]);c.push(this.b2a(l.join("&")).replace(/=+$/,""));return"//adx.adform.net/adx/?rp=4&"+c.join("&")+"&callback="+a},b2a:function(b){var d,a,f,c,l,k=0,g=0,h="",e=[];if(!b)return b;do d=b.charCodeAt(k++),a=b.charCodeAt(k++),f=b.charCodeAt(k++),c=d<<16|a<<8|f,d=63&c>>18,a=63&c>>12,f=63&c>>6,c&=63,e[g++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c);while(k<b.length);return h=e.join(""),l=b.length%3,(l?h.slice(0,l-3):h)+"===".slice(l||3)}};
AdTrack.DOM=function(){function b(){}var d=[];b.getIframeDocument=function(a){return a.contentDocument||a.contentWindow.document};b.getAllIframes=function(a,f,c){c="undefined"===typeof c||"number"!==typeof c?5:c;c=0>=c?1:c;var l=function(a){var g=0,h=setInterval(function(){if(g===c){var e=d;d=[];clearInterval(h);f(e);for(var m=0;m<e.length;m++){var n=b.getIframeDocument(e[m]);n&&l(n)}}else{e=a.getElementsByTagName("iframe");for(m=0;m<e.length;m++)-1===d.indexOf(e[m])&&d.push(e[m]);g++}},200)};l(a)};
return b}();
AdTrack.DOM.ClickProtection=function(){function b(){}b.createElement=function(b){var a=document.createElement("div");a.style.width="100%";a.style.height="100%";a.style.position="fixed";a.style.zIndex=b-1;a.style.top=0;a.style.left=0;a.style.cursor="default";return a};b.start=function(b){var a=!1;return setInterval(function(){AdTrack.Visibility.isVisible()?a&&(document.body.removeChild(b),a=!1):(document.body.appendChild(b),a=!0,b.style.cursor="default")},100)};b.stop=function(b){clearInterval(b)};return b}();
var outside="undefined"!=typeof module&&module.exports?module.exports:"undefined"!=typeof window&&window||this;outside.iframeCreator=iframeCreator;function iframeCreator(a,b,c,d){a={container:a||document.body,html:b||"",listeners:c||{},domain:d||document.domain,element:document.createElement("iframe"),resolved:!1,document:!1,window:!1};iframeCreator.append(a);iframeCreator.resolve(a)?iframeCreator.populate(a):iframeCreator.populate(a,document.domain);return a}
iframeCreator.append=function(a){iframeCreator.trigger(a,"onBeforeAppend");a.container.appendChild(a.element);iframeCreator.trigger(a,"onAfterAppend")};
iframeCreator.populate=function(a,b){b?(a.element.populate=iframeCreator.populate,a.element.src='javascript:(document.open().domain="'+b+'") && frameElement.populate(frameElement)'):(iframeCreator.resolve(a),iframeCreator.trigger(a,"onBeforePopulate"),a.element.frameElement=a.element,a.document.write(a.html),a.document.close(),iframeCreator.trigger(a,"onAfterPopulate"))};iframeCreator.trigger=function(a,b){var c=a.listeners[b];return c&&c(a,b)};
iframeCreator.resolve=function(a){try{a.window=a.element.contentWindow,a.document=a.element.contentDocument||a.window&&a.window.document}catch(b){}return a.resolved=!(!a.window||!a.document)};
AdTrack.Dispatcher=function(a,b,c,d,e,f,g,h,k){this.version=13;this.EUR2CZK=27.0187;this.USD2CZK=23.8197;this.brandingMinWidth=1200;this.brandingMaxScroll=160;this.time_performance=window.performance&&window.performance.now;this.time_start=this.time();this.type=a;this.domain=b;this.group=c;this.position=d;this.t=this.pass=this.status=0;this.events=[];this.debugMode=!1;this.debugTarget="AdTrackDebugConsole";this.keywordOrigin="online";this.cookiesEnabled=!0;this.reportMethod=null;this.channelMap=[];
if(this.url)this.url=f;else try{this.url=window.top.location.href}catch(l){this.url=document.referrer}if("track.us.org"==g||"http://track.us.org"==g)g="trackad.cz";this.server=g||"trackad.cz";this.aaproxy=h;this.keywordLogUrl=k||null;this.isOldIE=-1!==navigator.appVersion.indexOf("MSIE 10")||-1!==navigator.appVersion.indexOf("MSIE 9")||-1!==navigator.appVersion.indexOf("MSIE 8");this.isIE8=-1!==navigator.appVersion.indexOf("MSIE 8");this.isIE=-1!==navigator.userAgent.indexOf("MSIE");this.isOldOpera=
window.opera&&15>opera.version();this.isFirefox=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");this.isPhone=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i);this.isOldAndroid=0<=navigator.userAgent.indexOf("Android")&&2.3>=parseFloat(navigator.userAgent.slice(navigator.userAgent.indexOf("Android")+8));this.jsonpScript={};this.wordExtractor=new AdTrack.WordExtractor(document);e?e.options.noAsync?this.start(e):setTimeout(function(){this.start(e)}.bind(this),1):this.getDefinition()};
AdTrack.Price=function(a,b){this.price=a;this.originalPrice=b};AdTrack.Price.prototype={getPrice:function(){return this.price?this.price:null},getOriginalPrice:function(){return this.originalPrice?this.originalPrice:null}};AdTrack.Tier=function(a,b,c){a.debug("CREATE TIER "+b);this.track=a;this.method=b;this.channels=c};
AdTrack.Tier.prototype={initReportMethod:function(a){this.track.reportMethod||("adform-hbbtv"===a?(this.keywordOrigin="tv",a=new AdTrack.JsonPReport(this.track)):(this.keywordOrigin="online",a=new AdTrack.XhrReport(this.track)),this.track.reportMethod=a)},getChannel:function(a,b,c){if("sklik"==b.tag)return new AdTrack.SklikChannel(this.track,a,b,c);if("sklik-rtb"==b.tag)return new AdTrack.SklikRtbChannel(this.track,a,b,c);if("etarget-cz"==b.tag||"etarget-sk"==b.tag||"etarget-ro"==b.tag)return new AdTrack.EtargetChannel(this.track,
a,b,c);if("google"==b.tag)return new AdTrack.GoogleChannel(this.track,a,b,c);if("bb-rtb"==b.tag)return new AdTrack.BBRTBChannel(this.track,a,b,c);if("mads"==b.tag)return new AdTrack.MADSChannel(this.track,a,b,c);if("adform"==b.tag)return new AdTrack.AdformChannel(this.track,a,b,c);if("adform-na"==b.tag)return new AdTrack.AdformNAChannel(this.track,a,b,c);if("adform-bn"==b.tag)return new AdTrack.AdformBNChannel(this.track,a,b,c);if("adform-hbbtv"==b.tag)return new AdTrack.AdformHbbtvChannel(this.track,
a,b,c);if("adform-js-video"==b.tag)return new AdTrack.AdformJSVideChannel(this.track,a,b,c);if("adform-js-3rd"==b.tag)return new AdTrack.AdformJS3rdChannel(this.track,a,b,c);if("criteo"==b.tag)return new AdTrack.CriteoChannel(this.track,a,b,c);if("criteo-hb"==b.tag)return new AdTrack.CriteoHBChannel(this.track,a,b,c);if("appnexus"==b.tag)return new AdTrack.AppNexusChannel(this.track,a,b,c);this.doError("Unknown ad channel "+b.tag+"");return null},run:function(a,b,c){this.callback=c;this.definition=
a;this.track.debug("RUN TIER");if("split"==this.method){var d=0;c=[];for(var e=0;e<this.channels.length;e++){var f=Math.round(100*this.channels[e].weight);c[e]=[d,d+f];d+=f}if(0==d)return null;d*=Math.random();for(f=e=0;f<c.length;f++)if(d>=c[f][0]&&d<c[f][1]){e=f;break}this.t=e;this.initReportMethod(this.channels[e].chd.tag);this.track.debug("Split method win channel "+e+" - "+this.channels[e].chd.tag);c=this.track.getChannelCount(this.channels[e].chd.keys);this.track.evBidRequest(a,this.channels[e].chd,
c);c=this.getChannel(a,this.channels[e].chd,b);this.callback(c,this.channels[e].styles)}else if("hb"==this.method){this.timeout=1E4;this.requestStarts=[];this.hbChannels=[];this.hbResponses=0;this.hbEvaluated=!1;this.hbStart=(new Date).getTime();this.hbTimeouted=!1;a.options.noAsync?(this.hbTimer=null,this.track.debug("noAsync")):(this.hbTimer=setTimeout(function(){this.evalHB(!0)}.bind(this),this.timeout),this.track.debug("Async"));c=function(c){return function(){var d=this.track.getChannelCount(this.channels[c].chd.keys);
this.initReportMethod(this.channels[c].chd.tag);var e=this.track.getChannelKey(this.channels[c].chd,this.channels[c].styles.normal);this.track.evBidRequest(a,this.channels[c].chd,d);this.track.debug("Send bid "+c+" for "+this.channels[c].chd.tag+"#"+this.channels[c].chd.flag+", floor "+this.channels[c].floor);this.requestStarts[c]=this.track.time();this.hbChannels[c]=this.getChannel(a,this.channels[c].chd,b);this.hbChannels[c].bid(function(b,d){this.hbResponses++;this.track.debug("Bid back "+c);null!==
b&&!1==this.hbTimeouted?this.track.evBidResponse(a,this.channels[c].chd,b.getPrice(),!1,this.track.time()-this.requestStarts[c]):(!0==this.hbTimeouted&&(b=null),this.track.evBidResponse(a,this.channels[c].chd,b,!1,this.track.time()-this.requestStarts[c]));this.hbResponses==this.channels.length&&(this.hbTimer&&clearTimeout(this.hbTimer),this.evalHB(!1))}.bind(this),e)}};for(e=0;e<this.channels.length;e++)d=c(e).bind(this),a.options.noAsync?d():setTimeout(d,1);this.track.debug("Bids sent, waiting for responses")}else this.track.doError("Unknown tier method "+
this.method)},evalHB:function(a){this.hbTimeouted=a;if(!this.hbEvaluated){this.hbEvaluated=!0;this.hbEnd=(new Date).getTime();this.track.debug("EVALUATE - after "+(this.hbEnd-this.hbStart));for(var b=a=-1,c=0;c<this.hbChannels.length;c++){var d=this.hbChannels[c],e=d.price?d.price.getPrice():null,f=d.price?d.price.getOriginalPrice():0;this.track.debug("Channel "+d.chd.tag+"#"+d.chd.flag+" came with price "+e);e=f*this.channels[c].factor;e>=this.channels[c].floor&&e>a&&(a=e,b=c)}for(c=0;c<this.hbChannels.length;c++)c!==
b&&this.track.evPassback(this.definition,this.hbChannels[c].chd);-1!=b?(this.t=b,c=this.hbChannels[b],d=d.price?d.price.getPrice():null,this.track.debug("Won channel "+c.chd.tag+"#"+c.chd.flag+" with price "+d+" ("+a+")"),this.callback(c,this.channels[b].styles)):(this.track.debug("No responses came, go to next tier"),this.track.passback(this.definition,null));this.track.flushEvents()}}};
AdTrack.Dispatcher.prototype={getDefinition:function(){if(!this.isHidden()){var a="",a=this.aaproxy?this.aaproxy+"?":"//"+this.server+"/adtrack.php?"+this.uri("d",this.domain)+"&"+this.uri("m","mobile"==this.type?1:0)+"&"+this.uri("g",this.group)+"&"+this.uri("p",this.position)+"&",a=a+(this.uri("ext[url]",this.url)+"&"+this.uri("ext[dpi]",this.getDPI())+"&"),a=this.isPhone?270==window.orientation||90==window.orientation||-90==window.orientation?a+(this.uri("ext[screenWidth]",screen.height)+"&"+this.uri("ext[screenHeight]",
screen.width)):a+(this.uri("ext[screenWidth]",screen.width)+"&"+this.uri("ext[screenHeight]",screen.height)):a+(this.uri("ext[screenWidth]",screen.width)+"&"+this.uri("ext[screenHeight]",screen.height));this.isOldIE&&(a+="&"+this.uri("ext[isOldIE]",1));this.isIE&&(a+="&"+this.uri("ext[isIE]",1));this.isOldOpera&&(a+="&"+this.uri("ext[isOldOpera]",1));this.isFirefox&&(a+="&"+this.uri("ext[isFirefox]",1));this.isPhone&&(a+="&"+this.uri("ext[isPhone]",1));this.isOldAndroid&&(a+="&"+this.uri("ext[isOldAndroid]",
1));this.jsonp(a,"dclbk",function(a){a?a.options.noAsync?this.doError("Syncronous not supported for late rendering"):this.start(a):this.doError("No definition sent for late loading")}.bind(this))}},initEvents:function(){this.addEvent(this.window,"unload",function(){this.flushEvents()}.bind(this),!0);this.showEvent=this.createEvent("build")},start:function(a){this.debug("START");this.debug(a);this.setCookie("AdTrack-cookies",1,1);this.cookiesEnabled=this.getCookie("AdTrack-cookies")?!0:!1;if(this.isHidden())this.debug("should be hidden");
else{this.window=window;if(a.options.topFrame)try{window.top&&window.top.document&&(this.window=window.top)}catch(b){this.doError("Unable to perform topFrame rendering");return}this.document=this.window.document;this.initEvents();this.renderer=null;"flexi"==a.renderer?this.renderer=new AdTrack.FlexiRenderer(this,a):"fixed"==a.renderer?this.renderer=new AdTrack.FixedRenderer(this,a):"image"==a.renderer?this.renderer=new AdTrack.ImageRenderer(this,a):"sticky"==a.renderer?this.renderer=new AdTrack.StickyRenderer(this,
a):"branding"==a.renderer?this.renderer=new AdTrack.BrandingRenderer(this,a):this.doError("Unknown ad renderer "+a.renderer);if(this.renderer)if(a.options.compound)if(a.options.noAsync){var c=this.type+"_"+this.domain+"_"+this.group+"_"+this.position;if(AdTrack.units[c])if(1==AdTrack.units[c].status)this.debug("COMPOUND ADS - SECOND status 1");else if(2==AdTrack.units[c].status){var d=null;a.waterfall.tiers[AdTrack.units[c].pass-1].channels[AdTrack.units[c].t]&&(d=a.waterfall.tiers[AdTrack.units[c].pass-
1].channels[AdTrack.units[c].t]);this.debug("COMPOUND ADS - SECOND status 2");d&&d.chd.passback?eval(d.chd.passback):a.waterfall.passback?eval(a.waterfall.passback):this.doError("Passback is not defined for compound ad")}else this.doError("Unexpected status "+AdTrack.units[c].status+" in compound ad ");else this.debug("COMPOUND ADS - FIRST"),this.render(a)}else this.doError("Compound ads cannot be rendered in asynchronous mode");else this.render(a)}},render:function(a){this.debug("RENDER");var b,
c=this.document.readyState;if("complete"==c||"ready"==c||!this.isOldIE&&"interactive"==c){if(this.container=this.getContainer(a,!0))this.domAdjust(a),b={channel:null,style:null},this.openTier(a,this.pass,b)}else if(this.container=this.getContainer(a,!1))this.domAdjust(a),b={channel:null,style:null},this.openTier(a,this.pass,b);else{var d=this.document.addEventListener?"DOMContentLoaded":"readystatechange",e=function(){this.removeEvent.call(this.document,d,e);if(this.container=this.getContainer(a,
!0))this.domAdjust(a),b={channel:null,style:null},this.openTier(a,this.pass,b)}.bind(this);this.addEvent(this.document,d,e)}},getContainer:function(a,b){if(a.options.dom)if("container"==a.options.dom.method){var c=this.document.querySelector(a.options.dom.selector);if(c)return c;b&&this.doError("Unable to find c selector "+a.options.dom.selector)}else if("create"==a.options.dom.method)if(c=this.document.querySelector(a.options.dom.container)){var d=this.document.createElement("div");if(a.options.dom.before){var e=
c.querySelector(a.options.dom.before);if(e)return e.parentNode.insertBefore(d,e),d;if(a.options.dom.allowFallbackLast)return c.appendChild(d),d;b&&this.doError("Unable to find b selector "+a.options.dom.before+"")}else if(a.options.dom.after){if(e=c.querySelector(a.options.dom.after))return e.parentNode.insertBefore(d,e.nextSibling),d;if(a.options.dom.allowFallbackLast)return c.appendChild(d),d;b&&this.doError("Unable to find a selector "+a.options.dom.after+"")}else return c.appendChild(d),d}else b&&
this.doError("Unable to find s selector "+a.options.dom.container);else if("image"==a.options.dom.method){if(d=this.document.querySelector(a.options.dom.image))return d;b&&this.doError("Unable to find i selector "+a.options.dom.image)}else{if("fuzzyAfter"==a.options.dom.method){if(c=this.document.querySelector(a.options.dom.selector)){e=a.options.dom.fuzzyParentize?a.options.dom.fuzzyParentize:0;for(d=0;d<e&&c.parentNode&&(!a.options.dom.fuzzyParentizeAtMostClass||a.options.dom.fuzzyParentizeAtMostClass!=
c.parentNode.className)&&(!a.options.dom.fuzzyParentizeAtMostId||a.options.dom.fuzzyParentizeAtMostId!=c.parentNode.id);d++)c=c.parentNode;for(var e=this.document.createElement("div"),f=c,g=a.options.dom.fuzzyInject?a.options.dom.fuzzyInject:0,d=0;d<g;d++)c.parentNode.insertBefore(e,f.nextSibling),f=e,e=this.document.createElement("div");a.options.dom.fuzzyClass&&this.addClassName(e,a.options.dom.fuzzyClass);a.options.dom.fuzzyId&&e.setAttribute("id",a.options.dom.fuzzyId);a.options.dom.fuzzyStyle&&
(d="d"+Math.round(1E5*Math.random()),this.style("."+d+"{"+a.options.dom.fuzzyStyle+"}"),this.addClassName(e,d));c.parentNode.insertBefore(e,f.nextSibling);return e}b&&this.doError("Unable to find c selector "+a.options.dom.selector)}}else b&&this.doError("No dom definition");return null},domAdjust:function(a){this.debug("domAdjust");if(a.options.dom.remove)if(a.options.dom.remove instanceof Array)Array.prototype.forEach.call(a.options.dom.remove,function(a){(a=this.document.querySelector(a))&&a.parentNode.removeChild(a)}.bind(this));
else{var b=this.document.querySelector(a.options.dom.remove);b?b.parentNode.removeChild(b):this.doError("Unable to find r selector "+a.options.dom.remove)}},openTier:function(a,b,c){this.debug("openTier");var d=null,e=null;if(a.waterfall){if(a.waterfall.tiers.length<=b)return this.debug("No tier for pass "+b+" passabck"),this.debug(c.channel),c.channel&&this.evPassback(a,c.channel),a.waterfall.passback&&(this.debug("watter fall passback"),eval(a.waterfall.passback)),a.options.onPassback&&(this.debug("definition onPassback"),
eval(a.options.onPassback)),c.channel&&c.channel.passback&&(this.debug("channel passback"),eval(c.channel.passback)),this.status=2,!1;this.debug("Open tier, pass "+b);td=a.waterfall.tiers[b];b=new AdTrack.Tier(this,a.waterfall.tiers[b].method,a.waterfall.tiers[b].channels);b.run(a,e,function(b,c){this.channelMap[this.pass]=b;this.renderIfSpace(a,b,c)}.bind(this));return!0}if(a.aagun)return this.debug("AAGUN mode"),b=new AdTrack.Tier(this,"split",null),d=a.aagun.channel,e=a.aagun.data,channel=b.getChannel(a,
d.chd,e),this.renderIfSpace(a,channel,d.styles),!0},passback:function(a,b){this.debug("do passback");this.pass++;!0===this.openTier(a,this.pass,{channel:b})&&null!==b&&this.evPassback(a,b);this.flushEvents()},loaded:function(a,b,c,d,e){!d&&a.style&&(d=a.style);this.appendCss(d,a);this.renderer.loaded(d);this.evLoad(a,b,c,d);this._dispatchShow();this.status=1;a.options.onLoad&&(new Function("response","chd","var l = "+a.options.onLoad+".bind(this); l(response,chd)")).bind(this)(e,b);this.flushEvents()},
renderIfSpace:function(a,b,c){if(a.options.checkWidth){var d=b.chd.requiredWidth?b.chd.requiredWidth:b.chd.width?b.chd.width:0,e;e="viewport"==a.options.checkWidth?window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth:this.container.clientWidth;d>e?(this.debug("Not enough space: "+e),this.passback(a,b.chd,c?c.normal:null)):this.renderer.render(b,c)}else this.renderer.render(b,c)},getActualChannel:function(a,b){a||(a=this.pass);b||(b=this);return b.channelMap[a]?b.channelMap[a]:
null},style:function(a){this.styleElement||(this.styleElement=this.document.createElement("style"),this.document.getElementsByTagName("body")[0].appendChild(this.styleElement));try{this.styleElement.innerHTML+=" "+a}catch(b){this.styleElement.styleSheet.cssText+=" "+a}},addClassName:function(a,b){a.className+=(a.className?" ":"")+b;return a},getNS:function(a,b){return a.querySelectorAll("."+b)},setText:function(a,b){Array.prototype.forEach.call(a,function(a){a.innerHTML=b}.bind(this));return a},setAttribute:function(a,
b,c){Array.prototype.forEach.call(a,function(a){a.setAttribute(b,c)}.bind(this));return a},setOnclick:function(a,b,c){Array.prototype.forEach.call(a,function(a){this.addEvent(a,"click",b);a.onclick=c?"return true;":"return false;"}.bind(this));return a},setZoomin:function(a,b){Array.prototype.forEach.call(a,function(a){"scale"==b?(a.style.webkitTransform="scale(0.98,0.98)",a.style.MozTransform="scale(0.98,0.98)",a.style.msTransform="scale(0.98,0.98)",a.style.OTransform="scale(0.98,0.98)",a.style.transform=
"scale(0.98,0.98)"):"opacity"==b&&(a.style.opacity=0.5);a.style.transition="transform 5s, opacity 5s";a.style.transformOrigin="0% 0%";setTimeout(function(){this.measureImpress(a,function(d){"scale"==b?(a.style.webkitTransform="scale(1,1)",a.style.MozTransform="scale(1,1)",a.style.msTransform="scale(1,1)",a.style.OTransform="scale(1,1)",a.style.transform="scale(1,1)"):"opacity"==b&&(a.style.opacity=1)})}.bind(this),3E3)}.bind(this));return a},measureImpress:function(a,b){if(a.getBoundingClientRect){var c=
function(){try{var d=a.getBoundingClientRect();if("width"in d&&!d.width)return}catch(e){return}var f=d.right-d.left,g=d.bottom-d.top,h=this.window.innerHeight||this.document.documentElement.clientHeight||this.document.body.clientHeight,k=Math.max(0,Math.min(d.right,this.window.innerWidth||this.document.documentElement.clientWidth||this.document.body.clientWidth)-Math.max(d.left,0)),d=Math.max(0,Math.min(d.bottom,h)-Math.max(d.top,0)),f=k*d/(f*g);this.debug(f);0.7<f&&(this.removeEvent(this.window,
"resize",c),this.removeEvent(this.window,"scroll",c),this.removeEvent(this.window,"build",c),b(a,f))}.bind(this);this.addEvent(this.window,"resize",c);this.addEvent(this.window,"scroll",c);this.addEvent(this.window,"build",c)}},measureImpressBranding:function(a,b){var c=function(){var d="CSS1Compat"===(this.document.compatMode||""),d=void 0!==this.window.pageXOffset?this.window.pageYOffset:d?this.document.documentElement.scrollTop:this.document.body.scrollTop;if(this.document.documentElement.clientWidth>=
this.brandingMinWidth||d<=this.brandingMaxScroll)try{var e=a.getBoundingClientRect();if("width"in e&&!e.width)m=null;else var f=e.right-e.left,g=e.bottom-e.top,h=this.window.innerHeight||this.document.documentElement.clientHeight||this.document.body.clientHeight,k=Math.max(0,Math.min(e.right,this.window.innerWidth||this.document.documentElement.clientWidth||this.document.body.clientWidth)-Math.max(e.left,0)),l=Math.max(0,Math.min(e.bottom,h)-Math.max(e.top,0)),m=k*l/(f*g);this.removeEvent(this.window,
"resize",c);this.removeEvent(this.window,"scroll",c);b(a,m)}catch(n){}}.bind(this);this.addEvent(this.window,"resize",c);this.addEvent(this.window,"scroll",c);c()},styleizeAll:function(a){a=a.childNodes;0<a.length&&(this.styleize(a),Array.prototype.forEach.call(a,function(a){this.styleizeAll(a)}.bind(this)))},styleize:function(a){Array.prototype.forEach.call(a,function(a){if("function"==typeof a.hasAttribute&&a.hasAttribute("style")){var c=a.getAttribute("style");if(c){var d="d"+Math.round(1E7*Math.random());
this.style("."+d+"{"+c+"}");this.addClassName(a,d)}a.removeAttribute("style")}}.bind(this))},clearClass:function(a,b){Array.prototype.forEach.call(a,function(a){a.className=a.className.replace(b,"").trim();""==a.className&&a.removeAttribute("class")}.bind(this));return null},doError:function(a){this.debug("do error");this.debug(a);a="[C"+this.version+"] "+a+" ["+this.domain+" / "+this.type+" / "+this.group+" / "+this.position+" ("+this.pass+")]";this.log(a);a="//"+this.server+"/error.php?"+this.uri("m",
a)+"&"+this.uri("u",this.url);this.jsonp(a,"callback",function(a){}.bind(this))},evClick:function(a,b,c,d,e,f,g,h){var k=this.getChannelKey(b,h);this.getReportMethod().doClick(a,b,c,d,e,f,g,h,k)},evImpress:function(a,b,c,d){d=Math.round(100*d)/100;var e=this.getChannelKey(b,c);this.getReportMethod().doImpress(a,b,c,d,e);this.flushEvents()},evBidRequest:function(a,b,c){this.getReportMethod().doBidRequest(a,b,c);b&&b.tag&&"adform-hbbtv"===b.tag&&(a=this.wordExtractor.getWords(),0<a.length&&this.evKeywords(a))},
evBidResponse:function(a,b,c,d,e){this.getReportMethod().doBidResponse(a,b,c,d,e)},evPassback:function(a,b){this.getReportMethod().doPassback(a,b)},evLoad:function(a,b,c,d){var e=this.getChannelKey(b,d);this.getReportMethod().doLoad(a,b,c,d,e)},evKeywords:function(a,b){b||(b=this.keywordOrigin);null!=this.keywordLogUrl&&this.getReportMethod().doKeywords(a,b)},flushEvents:function(){this.getReportMethod().flushEvents()},uri:function(a,b){return a+"="+encodeURIComponent(b)},log:function(a){},time:function(){return Math.round(this.time_performance?
window.performance.now():(new Date).getTime())},isBanner:function(a){return 0<a.length?a[0].isBanner:!1},getDPI:function(){var a=document.createElement("div");a.setAttribute("style","height: 1in; position: absolute; width: 1in; top:-100px; left:-100px;");document.getElementsByTagName("body")[0].appendChild(a);var b=a.offsetHeight;document.body.removeChild(a);return b},rhtmlspecialchars:function(a){"string"==typeof a&&(a=a.replace(/&gt;/ig,">"),a=a.replace(/&lt;/ig,"<"),a=a.replace(/&#039;/g,"'"),
a=a.replace(/&quot;/ig,'"'),a=a.replace(/&amp;/ig,"&"));return a},noquerystring:function(a){return a.split("?")[0]},escapeRegExp:function(a){return a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")},createEvent:function(a){var b=document.createEvent("Event");b.initEvent(a,!1,!1);return b},addEvent:function(a,b,c){null!=a&&"undefined"!=typeof a&&(a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c)},removeEvent:function(a,b,c){null!=a&&"undefined"!=
typeof a&&(a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent?a.detachEvent("on"+b,c):a["on"+b]="")},jsonp:function(a,b,c){var d=("adTrackJSONP"+Math.random()).replace(".","");if(a=a+"&"+this.uri(b,d))window[d]=function(a,b){try{delete window[d]}catch(g){}try{this.jsonpScript[d]&&(this.jsonpScript[d].parentNode.removeChild(this.jsonpScript[d]),this.jsonpScript[d]=null,delete this.jsonpScript[d])}catch(h){}c&&c(a,b)}.bind(this),b=document.createElement("script"),b.setAttribute("src",
a),b.onerror=function(){c()},this.jsonpScript[d]=b,document.getElementsByTagName("head")[0].appendChild(b)},getDomainName:function(a){a=a.split(".").reverse();return 3<=a.length&&a[1].match(/^(com|edu|gov|net|mil|org|nom|co|name|info|biz|us)$/i)?a[2]+"."+a[1]+"."+a[0]:a[1]+"."+a[0]},setCookie:function(a,b,c){if(this.cookiesEnabled){var d=new Date;d.setTime(d.getTime()+1E3*c);c="expires="+d.toUTCString();document.cookie=a+"="+b+"; "+c+";domain="+this.getDomainName(document.location.host)+"; Path=/"}else a=
{k:a,v:b,x:c},b="//"+this.server+"/cookie.php",c=new XMLHttpRequest,c.addEventListener("load",function(a){console.log(a.target.responseText)}),c.open("POST",b,!0),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.send("cookie="+AdTrack.JSON.stringify(a))},getCookie:function(a){if(this.cookiesEnabled){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}a=
"//"+this.server+"/cookie.php?"+this.uri("k",a);b=new XMLHttpRequest;b.open("GET",a,!1);b.send();return 200===b.status?b.responseText:""},addImp:function(a){var b=this.getCookie("AdTrack-imp-"+this.domain+"-"+this.type+"-"+this.group+"-"+this.position);b?b++:b=1;this.setCookie("AdTrack-imp-"+this.domain+"-"+this.type+"-"+this.group+"-"+this.position,b,a);return b},setHide:function(a){this.setCookie("AdTrack-hide-"+this.domain+"-"+this.type+"-"+this.group+"-"+this.position,1,a)},isHidden:function(){return this.getCookie("AdTrack-hide-"+
this.domain+"-"+this.type+"-"+this.group+"-"+this.position)},getChannelKey:function(a,b){return null==b||0==b.length?(this.debug("get channel key without style"),a.keys[1]?a.keys[1]:null):b.count?a.keys[b.count]?a.keys[b.count]:null:null},appendCss:function(a,b){var c=this.document.createElement("style");if(a&&a.options&&a.options.css){this.document.getElementsByTagName("head")[0].appendChild(c);try{c.innerHTML=a.options.css}catch(d){c.styleSheet.cssText=a.options.css}}else if(b&&b.options&&b.options.css){this.document.getElementsByTagName("head")[0].appendChild(c);
try{c.innerHTML=b.options.css}catch(e){c.styleSheet.cssText=b.options.css}}},getChannelCount:function(a){a=Object.keys(a);return a[0]?a[0]:0},setDebugMode:function(){this.debugMode=!0},debug:function(a){if(this.debugMode){var b=document.getElementById(this.debugTarget);"object"===typeof a?null!=b&&(b.value+="\n"+a):null!=b?b.value+="\n"+this.position+"/"+this.group+" "+a:console.log("[DEBUG]"+this.position+"/"+this.group+" "+a)}},getReportMethod:function(){this.reportMethod||(this.reportMethod=new AdTrack.XhrReport(this));
return this.reportMethod},_dispatchShow:function(){this.window.dispatchEvent(this.showEvent)}};
AdTrack.ConsoleReport=function(a){this.track=a};AdTrack.ConsoleReport.prototype={doClick:function(a,b,c,d,e,f,g,h){this.track.debug("[Dummy reporter] Do click")},doLoad:function(a,b,c,d){this.track.debug("[Dummy reporter] Do load")},doPassback:function(a,b){this.track.debug("[Dummy reporter] Do passback")},doBidResponse:function(a,b,c,d,e){this.track.debug("[Dummy reporter] Do bid response")},doBidRequest:function(a,b,c){this.track.debug("[Dummy reporter] Do bid request")},flushEvents:function(){this.track.debug("[Dummy reporter] Flush events")}};
AdTrack.JsonPReport=function(b){this.track=b;this.jsonpScript=[]};
AdTrack.JsonPReport.prototype={doClick:function(b,a,c,d,e,h,f,g,k){a="//"+this.track.server+"/click.php?"+this.doP(b,a)+"&"+this.track.uri("key",k)+"&"+this.track.uri("u",this.track.url);h&&(a+="&"+this.track.uri("z",h));g&&(a+="&"+this.track.uri("s",g.name));e&&(a+="&"+this.track.uri("i",e));c&&(a+="&"+this.track.uri("x",c));d&&(a+="&"+this.track.uri("y",d));this.jsonp(a,"callback",function(a){if(!b.options.newwindow&&null!==f)try{window.top.history.pushState&&(this.track.isFirefox||this.track.isOldOpera)&&
window.top.history.pushState({},document.title,window.top.location.href),window.top.location.assign(f)}catch(c){window.top.location.href=f}}.bind(this))},doLoad:function(b,a,c,d,e){c=c||0;b="//"+this.track.server+"/load.php?"+this.doP(b,a)+"&"+this.track.uri("l",c)+"&"+this.track.uri("key",e)+"&"+this.track.uri("u",this.track.url);d&&(b+="&"+this.track.uri("s",d.name));this.jsonp(b,"callback",function(a){}.bind(this))},doPassback:function(b,a){var c="//"+this.track.server+"/passback.php?"+this.doP(b,
a)+"&"+this.track.uri("u",this.track.url);this.jsonp(c,"callback",function(a){}.bind(this))},doBidResponse:function(b,a,c,d,e){b="//"+this.track.server+"/bidResponse.php?"+this.doP(b,a,e)+"&"+this.track.uri("w",d)+"&"+this.track.uri("u",this.track.url);c&&(b+="&"+this.track.uri("pr",c));this.jsonp(b,"callback",function(a){}.bind(this))},doBidRequest:function(b,a,c){c=c||0;b="//"+this.track.server+"/bidRequest.php?"+this.doP(b,a)+"&"+this.track.uri("l",c)+"&"+this.track.uri("u",this.track.url);this.jsonp(b,
"callback",function(a){}.bind(this))},doImpress:function(b,a,c,d,e){b="//"+this.track.server+"/impress.php?"+this.doP(b,a)+"&"+this.track.uri("coeff",d)+"&"+this.track.uri("s",c?c.name:null)+"&"+this.track.uri("key",e)+"&"+this.track.uri("u",this.track.url);this.jsonp(b,"callback",function(a){}.bind(this))},doKeywords:function(b,a){var c=null!==this.track.keywordLogUrl?this.track.keywordLogUrl:null;null!==c&&(c=c+"/keywords/?"+this.track.uri("keywords",b)+"&"+this.track.uri("origin",a),this.jsonp(c,
"callback",function(a){}.bind(this)))},flushEvents:function(){},doP:function(b,a,c){b=this.track.time();a=this.track.uri("d",this.track.domain)+"&"+this.track.uri("m","mobile"==this.track.type?1:0)+"&"+this.track.uri("c",a.tag)+"&"+this.track.uri("cf",a.flag?a.flag:"")+"&"+this.track.uri("g",this.track.group)+"&"+this.track.uri("p",this.track.position)+"&"+this.track.uri("t",b-this.track.time_start);c&&(a+="&"+this.track.uri("rt",c));return a},jsonp:function(b,a,c){var d=("adTrackJSONP"+Math.random()).replace(".",
"");if(b=b+"&"+this.track.uri(a,d))window[d]=function(a,b){try{delete window[d]}catch(f){}try{this.jsonpScript[d]&&(this.jsonpScript[d].parentNode.removeChild(this.jsonpScript[d]),this.jsonpScript[d]=null,delete this.jsonpScript[d])}catch(g){}c&&c(a,b)}.bind(this),a=document.createElement("script"),a.setAttribute("src",b),a.onerror=function(){c()},this.jsonpScript[d]=a,document.getElementsByTagName("head")[0].appendChild(a)}};
AdTrack.XhrReport=function(a){this.events=[];this.track=a};
AdTrack.XhrReport.prototype={doClick:function(a,c,b,d,e,h,f,g,k){this.evEvent(a,c,"click",{x:b,y:d,i:e,z:h,s:g?g.name:null,key:k});this.flushEvents();if(!a.options.newwindow&&null!==f)try{window.top.history.pushState&&(this.track.isFirefox||this.track.isOldOpera)&&window.top.history.pushState({},document.title,window.top.location.href),window.top.location.assign(f)}catch(l){window.top.location.href=f}},doLoad:function(a,c,b,d,e){this.evEvent(a,c,"load",{c:b,s:d?d.name:null,key:e})},doPassback:function(a,
c){this.evEvent(a,c,"passback",null)},doBidResponse:function(a,c,b,d,e){this.evEvent(a,c,"bid_response",b?{p:b,w:d}:{w:d},e)},doBidRequest:function(a,c,b){this.evEvent(a,c,"bid_request",{c:b})},doImpress:function(a,c,b,d,e){this.evEvent(a,c,"impress",{coeff:d,s:b?b.name:null,key:e})},doKeywords:function(a,c){var b=null!==this.track.keywordLogUrl?this.track.keywordLogUrl:null;if(null!==b){var d=new XMLHttpRequest;d.open("POST",b+"/event/",!0);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
d.send("keywords="+JSON.stringify(a)+"&origin="+JSON.stringify(c))}},flushEvents:function(){if(0<this.events.length){var a=this.events;this.events=[];var c="//"+this.track.server+"/event.php?"+this.track.uri("d",this.track.domain)+"&"+this.track.uri("m","mobile"==this.track.type?1:0)+"&"+this.track.uri("g",this.track.group)+"&"+this.track.uri("p",this.track.position)+"&"+this.track.uri("u",this.track.url),b=new XMLHttpRequest;b.open("POST",c,!0);b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
b.send("events="+AdTrack.JSON.stringify(a));b.addEventListener("load",function(a){}.bind(this))}},evEvent:function(a,c,b,d,e){a=this.track.time()-this.track.time_start;this.events.push({rt:e,t:a,e:b,c:c?c.tag:null,cf:c?c.flag:null,v:d})}};
AdTrack.WordExtractor=function(a){this.dom=a;this.keyword=[];this.minLength=4;this.stopWordsCZ="a;aby;aj;ale;anebo;ani;ani\u017e;ano;asi;av\u0161ak;a\u017e;ba;bez;bude;budem;bude\u0161;by;byl;byla;byli;bylo;b\u00fdt;\u010di;\u010dl\u00e1nek;\u010dl\u00e1nku;\u010dl\u00e1nky;co;\u010dom;co\u017e;cz;dal\u0161\u00ed;dal\u0161\u00edch;do;dnes;ho;i;jak;jak\u00e9;jako;je;jeho;jej;jej\u00ed;jejich;jen;je\u0161t\u011b;jen\u017e;ji;jin\u00e9;ji\u017e;jsem;jses;jsi;jsme;jsou;jste;k;kam;kde;kdo;kdy\u017e;ke;kter\u00e1;kter\u00e9;kte\u0159\u00ed;kterou;kter\u00fd;ku;m\u00e1;m\u00e1te;m\u00e9;mezi;mi;m\u00edt;mne;mn\u011b;mnou;m\u016fj;m\u016f\u017ee;my;na;nad;n\u00e1m;napi\u0161te;n\u00e1s;na\u0161\u00ed;na\u0161i;ne;nebo;nebo\u0165;nech\u0165;nejsou;nen\u00ed;net;ne\u017e;n\u00ed;nic;nov\u00e9;nov\u00fd;n\u00fdbr\u017e;o;od;ode;on;org;pak;po;pod;podle;pokud;pouze;pr\u00e1v\u011b;p\u0159ed;p\u0159es;p\u0159i;pro;pro\u010d;proto;proto\u017ee;prvn\u00ed;pt\u00e1;re;s;se;si;sice;spol;strana;sv\u00e9;sv\u016fj;sv\u00fdch;sv\u00fdm;sv\u00fdmi;ta;tak;tak\u00e9;tak\u017ee;tamhle;tato;tedy;t\u00e9ma;t\u00e9;ten;tedy;tento;teto;tim ;timto;tipy;to;tohle;toho;tohoto;tom;tomto;tomuto;totiz;tu;tudiz;tuto;tvuj;ty;tyto;u;u\u017e;v;v\u00e1m;v\u00e1s;va\u0161e;ve;vedle;v\u00edce;v\u0161ak;v\u0161echen;vy;v\u017edy\u0165;z;za;zda;zde;ze;zp\u011bt;zpr\u00e1vy".split(";");
this.stopWordsEN="a about above across after again against all almost alone along already also although always among an and another any anybody anyone anything anywhere are area areas around as ask asked asking asks at away b back backed backing backs be became because become becomes been before began behind being beings best better between big both but by c came can cannot case cases certain certainly clear clearly come could d did differ different differently do does done down down downed downing downs during e each early either end ended ending ends enough even evenly ever every everybody everyone everything everywhere f face faces fact facts far felt few find finds first for four from full fully further furthered furthering furthers g gave general generally get gets give given gives go going good goods got great greater greatest group grouped grouping groups h had has have having he her here herself high high high higher highest him himself his how however i if important in interest interested interesting interests into is it its itself j just k keep keeps kind knew know known knows l large largely last later latest least less let lets like likely long longer longest m made make making man many may me member members men might more most mostly mr mrs much must my myself n necessary need needed needing needs never new newer newest next no nobody non noone not nothing now nowhere number numbers o of off often old older oldest on once one only open opened opening opens or order ordered ordering orders other others our out over p part parted parting parts per perhaps place places point pointed pointing points possible present presented presenting presents problem problems put puts q quite r rather really right right room rooms s said same saw say says second seconds see seem seemed seeming seems sees several shall she should show showed showing shows side sides since small smaller smallest so some somebody someone something somewhere state states still still such sure t take taken than that the their them then there therefore these they thing things think thinks this those though thought thoughts three through thus to today together too took toward turn turned turning turns two u under until up upon us use used uses v very w want wanted wanting wants was way ways we well wells went were what when where whether which while who whole whose why will with within without work worked working works would x y year years yet you young younger youngest your yours z zero safeframe container".split(" ")};
AdTrack.WordExtractor.prototype={log:function(){},getWords:function(){var a=[],a=this.getMetadata().concat(a),a=this.getTitle().concat(a);this.keyword=a=this.getH1().concat(a);this.removeStopWords();return this.keyword},getMetadata:function(){var a=this.dom.querySelector('meta[name="keywords"]');if(null==a)return[];for(var a=a.getAttribute("content"),a=this.replaceChar(a),a=this.splitWords(a),b=[],c=0;c<a.length;c++){var d=a[c].trim();""!=d&&b.push(d)}return b},getTitle:function(){var a=this.dom.title,
a=this.replaceChar(a);return a=this.splitWords(a)},getH1:function(){for(var a=this.dom.getElementsByTagName("h1"),b=[],c=0;c<a.length;c++)var d=a[c].innerHTML,d=this.replaceChar(d),b=this.splitWords(d).concat(b);return b},replaceChar:function(a){a=a.replace(/<[a-zA-Z][^>]*>/g," ");a=a.replace(/<\/[a-zA-Z][^>]*>/g," ");a=a.replace(/\&[a-z]+;/g," ");a=a.replace(/  +/g," ");return a=a.trim()},splitWords:function(a){if(null==a)return[];for(var b=a.split(" "),c=[],d=new RegExp(/[a-z\u00e1\u010d\u010f\u00e9\u011b\u00ed\u0148\u00f3\u0159\u0161\u0165\u016f\u00fa\u00fd\u017e]+/g),
e=0;e<b.length;e++)""!=b[e]&&(a=b[e].toLowerCase().match(d),null!=a&&"undefined"!=a&&(c=c.concat(a)));return c},generateURL:function(){this.getWords();if(0==this.keyword.length)return"";for(var a="&mkw=",b=0;b<this.keyword.length;b++)0!=b&&(a+=","),a+=encodeURI(this.keyword[b]);return a},generateCSV:function(){this.getWords();if(0==this.keyword.length)return"";for(var a="",b=0;b<this.keyword.length;b++)0!=b&&(a+=","),a+=encodeURI(this.keyword[b]);return a},removeStopWords:function(){for(var a=[],
b,c=0;c<this.keyword.length;c++)b=this.keyword[c].toLowerCase(),-1==this.stopWordsCZ.indexOf(b)&&-1==this.stopWordsEN.indexOf(b)&&-1==a.indexOf(b)&&b.length>=this.minLength&&a.push(b);this.keyword=a}};
AdTrack.units["classic_root.cz_article_fixed"]=new AdTrack.Dispatcher("classic", "root.cz", "article", "fixed", null, null, "trackad.cz", null, "https://log.trackad.cz");
// 1ms
