/***********************************************************************/
/*                                                                     */
/*  FILE        :inthandler.c                                          */
/*  DATE        :Sat, May 09, 2015                                     */
/*  DESCRIPTION :Interrupt Handler                                     */
/*  CPU TYPE    :H8S/Other                                             */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
     



												
#include "inthandler.h"

//   vector 1 Manual Reset
void INT_Manual_Reset(void)  { }

