/***********************************************************************/
/*                                                                     */
/*  FILE        :C_Asm.c                                               */
/*  DATE        :Wed, Feb 22, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8S/Other                                             */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         
#include "iodefine.h"

void 	proc2(char *a, short b, char c);

char 	aaa[] = "UPRAVOVANY TEXT";
short	bbb;
char	ccc;

/* direktiva -mno-quickcall v nastaveni options pro preklad */
/* vynuti pouziti zasobniku pro prenos argumentu */

int main(void) {

	bbb = 20;
	ccc = 'X';

	proc2(aaa,bbb,ccc);
		
    while (1) {
	}
    return 0;
}

void proc2(char *a, short b, char c){	
	short	xxx;
	char	yyy;
	
	a[b] = c;	
	xxx = 100;
	yyy = 100;
	
}



