/***********************************************************************/
/*                                                                     */
/*  FILE        :iodefine.h                                            */
/*  DATE        :Sat, May 09, 2015                                     */
/*  DESCRIPTION :Definition of I/O Register                            */
/*  CPU TYPE    :H8S/Other                                             */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         

#ifndef IODEFINE_H 
#define IODEFINE_H

/****************************************************************
  iodefine.h

  Please add the definitions of the internal register addresses
  depending on your CPU.

*****************************************************************/

#endif

